language: python

cache: pip

python:
- 2.7.10
- 2.7.11
script:
- "echo $TRAVIS"
- "echo $testvar"
- "echo Unit Tests"
- "python manage.py test firstapp.tests.test_ut"
- "echo Integration Tests"
- "python manage.py test firstapp.tests.test_it"
env:
  global:
  - secure: Z7NLWJrEhHit0utCUhM0ZjLJ270l2fqOMxYYUTUH+XWG4xbAZXEUBMAk1y/J+7m4t9n8J0FY9pxSIMKn4sElt4xW8YYI4gEn49NExsmWymak32Zj9iXEWIODYej85SxPlSL8rcDFK2gd+CeSslxIzv30f3q8GgtJ2qgyaXsy7ZtwZiXufv8/t9b91taCiOJSDmmNesyB2NXnMoHocEia5tMRukIy3Th7vYVwCqvBWCTzdaHDOaPpmczhp3sLvtHSimMCqCGAqVxFr/EWBmyxgvyxIaSnwC4P/graM0YWI9DryFP3uAZwnYvf5GQzA0PIhmF7S9bPUUYwWPA5bc8V26w4VPCZvAO40aYZEKdKrd7fFU+8YT/haN9V/rB2hVGnbeKzJNvIiFHLYvfwnbw423jab3X/vF2cqvaRPhC0ErDxl7nfBxwTAQYF3QClmAvx6ejGHVHZgXVzD1RFROnoFrxoOTMpELTadvDGO+gb1ITYebZJqLwJZSBMYscQVYySaOY4PwP/vvozYzY/JTp4F+m+PU5BuBHXqk0C3meazA2z4Xqsmvd74YU1b/VOgJgZ5OEV7mhEutu6iZ24bhoeOm29626YQlTxQDUpeaI4ELMHX1dr2+QhmDkQCawxBkG6AxOXToGVTfQJnbYBV0udEwv9BliL2Zek+Vpt1hfiu4A=
  - secure: KHWe7ZAbSpDoI10MtboEuaPT/yqWIZiU10x/OQV5DI4VdM1iCDOIpYaI6IitxSKbF8KmCMvl1VG7iNomYfkBSEbgjDZY30h+Nv6t1Ns9Pl/YnBtoqdRYhgWQraVp2U4FneP4nEGBuDEjNiFYsQiljeOZQhVo86RSa9CNODFQ70iBbmE/IxM4eVwr2QkRpEeDmMOuSqOJLJPiqrUMCfgGyOJRXQecMN1WlakYshAI+lUVIaLPYveQmff2PYn3WQ+1fKvjr1fjwjkjxuz9Nu/qrBAcbUOsEbXl+zgGa8j46tUYABaVvapUd/j5/EiCog9sOdJPcOJIYClp6tZDTFFFRpoeqEtA5yQUaNbIpXX/PU5k5YwJe2gNP4Fp0OE0CwtaBVOorYzP1DgNpv0GzlzLvUW0xtAeB7JIIIy12zimtm9B5PsYz+x5MgNEZsSlSOWt3Z4HDI4g/Lnd/++SGBWPvYUUH+TRhOZFe2RckOKB/ENnpV1Xl599e2FLLFg/cooYC7w0wZ2Ulln723EVMKeKIPnrWBsqq9dxVU1CGnUoy2AQ+k631YhA3To2jcqfx80ZtZTxGrHmt9DoqmgUmzI1SwjQRrbymO9ao/11bqVuqQiNSxxxBOgTQkVHLV2xQjx1fWRw4AOxBoZ9Y/jx1IfqtHinoJ2FbcC31hdJC7+3opQ=
  - secure: gtnSf7UqVz0IrB6SNpD8x2whF58DbSZIRkQMXKmKucZ941ot/WbROj16bIF9y+ID2+G6GDIa7mHtEUjVNaDeokoHfC+/1mLIMNt+YGzvhn9VL9horEVlVyOYxWJws7rAvBK8Bfp6luVgo746t4VLAuxyw11F3/UkfJXTRzQy8gRUJZMcDcmRpsjSGOhNneUq1Z69bW6qycYJGic+fh3OPms3IUMFnneHptFwVQQSqIBTOgT0vCZvNwp/bXKkw1ro1h+fxfeZsNE3INoGpuxGdGUSiNKS+HpRvpBcTupqQRvxN88bMScKcb84omOqq9Fus0SRixBLK0UMOYp+BoDWis83/7Xtgm8t49ddzIQteyphBW5TOsnAczuwi8EuzxMMQUEgMigJgjr/z63BQzyNCa7p741R18JC/VJiGoosGh9sFquIogt75C/FDS5IqzCyc08tMcLSO5feBeLbqIt4EsHSsn+yip1sjW0gzhOkkUF7BZ0dS+oqbGcaohdPkg0xZONELUlSHF4bwrgRr9EBYc2TAxD9nuJONM+TRDu7p4ervKyVwMvUgP9vT72ium3CEZ35UdMGXyhSM7HWhQTewGbL35M4N6XxJ4o+wTKD58FMYcCHa8YLY9Z1wUa1PLifiInpRBoRRcOcSaIwG5JQdf6bGURrlw6r7/xCt73x43Y=

